### ISSUE TITLE
消耗流量问题

### ISSUE THREAD

**Issue by feng1m8** [yangchenxi/BiliMusicPlayer#3]
请问加载歌曲消耗流量和加载视频一样吗? 希望可以说明一下低音质和高音质消耗流量分别对应什么清晰度的视频，或者是直接走音频的流量，谢谢啦。

**Comment by despcy** [comment]
大部分视频都是有对应的audio资源的，优先加载。详见API：https://github.com/yangchenxi/Bilibili-MusicPlayer/blob/V2.0/Core/DownloadInfo.md
